8 macros
helo-head/Tally-Core2 pull request #9
Opened 2023-01-31 22:04 UTC by helo-head

In theory the new changes to both the buttonWasPressed() updatemacrobutton() should resolve the issues I noted earlier. I kept isPressed as it still seems to work. If we run into issues it can always be replaced with  true/false.

2023-01-31 22:20 UTC, brianteeman commented
will test in the morning and feedback

2023-02-01 10:26 UTC, brianteeman commented
This seems to work. As I press a macro I can see it change colors and then revert on release. So the indication that you have pressed a macro button is correct.

For my own purposes I will probably add some code to indicate the last macro button pressed as I am using the macro to set the atem on air and there is no method in the skaarhoj library to get the onair status

2023-02-01 10:28 UTC, brianteeman requested changes
just typos - no code change

2023-02-01 10:28 UTC, brianteeman commented on Tallly-Core2-V11.ino
> +/// Button press function
```suggestion
// Button press function
```

2023-02-01 10:28 UTC, brianteeman commented on Tallly-Core2-V11.ino
> +  if (!postConfig) {                  //Update file selection button appropriatly
```suggestion
  if (!postConfig) {                  // Update file selection button appropriately
```

2023-02-01 10:28 UTC, brianteeman commented on Tallly-Core2-V11.ino
> +  if ( e.type == E_TOUCH) {           // If a touch event set ATEM appropriatly and update the button if a maco
```suggestion
  if ( e.type == E_TOUCH) {           // If a touch event set ATEM appropriately and update the button if a macro
```

2023-02-01 10:28 UTC, brianteeman commented on Tallly-Core2-V11.ino
> +  } else {                            // Release handler for macros to update button appropriatly
```suggestion
  } else {                            // Release handler for macros to update button appropriately
```

2023-02-01 13:19 UTC, brianteeman commented on Tallly-Core2-V11.ino
> +  } //End camera/macro button handling
```suggestion
  } // End camera/macro button handling
```

2023-02-01 14:58 UTC, helo-head commented
> For my own purposes I will probably add some code to indicate the last macro button pressed as I am using the macro to set the atem on air and there is no method in the skaarhoj library to get the onair status

Actually that makes sense, I like it. Seems like it would be easy enough to add, just a call to draw all the macrobutons on TOUCH effectively resetting the last one called and then a change in color on RELEASE to reflect it was the last one called.... I can add this in if you like ?

2023-02-01 15:02 UTC, brianteeman commented
Yes that would be great if you could.

I also found an interesting [modification ](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266) to the bmd library that adds support for detecting the streaming status. 

That would allow for an **ON AIR** label

2023-02-01 15:08 UTC, merged